apiVersion: v1
kind: PersistentVolume
metadata:
  name: data
  namespace: influxdb
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: microk8s-hostpath
  hostPath:
    path: /mnt/influxdb/

